services:
  app:
    build: .
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
    depends_on:
      - db

  db:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data: